# Generated by Django 6.0.1 on 2026-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_description_alter_car_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_photo",
            field=models.ImageField(max_length=255, upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_photo_1",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_photo_2",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_photo_3",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_photo_4",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
    ]
